name: UKOTHDEV Deploying

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USER }}
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        source: "."
        target: "/var/www/"

    - name: Install dependencies
      run: |
        ssh root@your_droplet_ip << 'EOF'
        cd /var/www/ukothdev
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        EOF

    - name: Restart Gunicorn
      run: |
        ssh root@161.35.72.151 << 'EOF'
        cd /var/www/ukothdev
        pkill gunicorn || true
        source venv/bin/activate
        gunicorn -w 4 -b 127.0.0.1:8000 app:app &
        EOF
