name: CI/CD Pipeline

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

    - name: Add DigitalOcean host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USER }}
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        source: "."
        target: "/var/www/ukothdev"

    - name: Install dependencies
      run: |
        ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
        cd /var/www/ukothdev
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        EOF

    - name: Restart Gunicorn
      env:
        DATABASE_URI: ${{ secrets.MYSQL_URI }}
      run: |
        ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
        sudo systemctl daemon-reload
        sudo systemctl restart ukothdev
        EOF